
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: sdv_image_flask
        container_name: flask_visualizer
        ports:
            - "5005:5000"
        volumes:
            - .:/app
        environment:
            FLASK_DEBUG: "1"
            